/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowServiceHome (void);
GtkWidget* create_windowServiceAjout (void);
GtkWidget* create_windowServiceModif (void);
GtkWidget* create_windowServiceSup (void);
GtkWidget* create_windowServiceAffectation (void);
